/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...slug]': RouteRecordInfo<
      '/[...slug]',
      '/:slug(.*)',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/chat': RouteRecordInfo<
      '/chat',
      '/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/courses/': RouteRecordInfo<
      '/courses/',
      '/courses',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'learn': RouteRecordInfo<
      'learn',
      '/courses/learn/:courseId',
      { courseId: ParamValue<true> },
      { courseId: ParamValue<false> },
      | never
    >,
    '/setting': RouteRecordInfo<
      '/setting',
      '/setting',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/smart.chat': RouteRecordInfo<
      '/smart.chat',
      '/smart/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/word-book': RouteRecordInfo<
      '/word-book',
      '/word-book',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/views/[...slug].vue': {
      routes:
        | '/[...slug]'
      views:
        | never
    }
    'src/views/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/views/chat.vue': {
      routes:
        | '/chat'
      views:
        | never
    }
    'src/views/courses/index.vue': {
      routes:
        | '/courses/'
      views:
        | never
    }
    'src/views/courses/learn/[courseId].vue': {
      routes:
        | 'learn'
      views:
        | never
    }
    'src/views/setting.vue': {
      routes:
        | '/setting'
      views:
        | never
    }
    'src/views/smart.chat.vue': {
      routes:
        | '/smart.chat'
      views:
        | never
    }
    'src/views/word-book.vue': {
      routes:
        | '/word-book'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
